---
- name: Prepare TLS Environment
  hosts: all
  become: true

  tasks:
    # RedHat 9 images have curl-minimal which conflicts with curl
    # curl-minimal is sufficient for our health endpoint testing
    - name: Install curl for health endpoint testing | Debian
      package:
        name: curl
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Create miarec group
      group:
        name: miarec
        state: present

    - name: Include TLS certificate generation tasks
      include_tasks: tasks/certificates.yml

    - name: Include PostgreSQL TLS setup tasks
      include_tasks: tasks/postgresql_tls.yml

    - name: Include Redis TLS setup tasks
      include_tasks: tasks/redis_tls.yml
