---
- name: Restart miarec
  service:
    name: miarec
    state: restarted
  become: true

- name: Start miarec
  service:
    name: miarec
    state: started
  become: true

- name: Restart sshd
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
  become: true
  ignore_errors: true
