---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

    - set_fact:
        miarec_version: "{{ lookup('env', 'MIAREC_VERSION') }}"

  roles:
    - role: ansible-role-miarec
      tags:
        - miarec
